Final Assignment1/Controllers/Models1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final_Assignment1.Models;

namespace Final_Assignment1.Controllers
{
    public class Models1Controller : Controller
    {
        private OurConnection db = new OurConnection();

        // GET: Models1
        public ActionResult Index()
        {
            var model = db.Model.Include(m => m.VehicleType);
            return View(model.ToList());
        }

        // GET: Models1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: Models1/Create
        public ActionResult Create()
        {
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name");
            return View();
        }

        // POST: Models1/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModelId,Engine_Size,Number_of_Doors,Colour,VehicleTypeId")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Model.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // GET: Models1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // POST: Models1/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ModelId,Engine_Size,Number_of_Doors,Colour,VehicleTypeId")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // GET: Models1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Models1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Model.Find(id);
            db.Model.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final Assignment1/Controllers/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final_Assignment1.Models;

namespace Final_Assignment1.Controllers
{
    public class VehicleTypesController : Controller
    {
        private OurConnection db = new OurConnection();

        // GET: VehicleTypes
        public ActionResult Index()
        {
            return View(db.VehicleType.ToList());
        }

        // GET: VehicleTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleType vehicleType = db.VehicleType.Find(id);
            if (vehicleType == null)
            {
                return HttpNotFound();
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleTypeId,Name")] VehicleType vehicleType)
        {
            if (ModelState.IsValid)
            {
                db.VehicleType.Add(vehicleType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleType vehicleType = db.VehicleType.Find(id);
            if (vehicleType == null)
            {
                return HttpNotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleTypeId,Name")] VehicleType vehicleType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleType vehicleType = db.VehicleType.Find(id);
            if (vehicleType == null)
            {
                return HttpNotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VehicleType vehicleType = db.VehicleType.Find(id);
            db.VehicleType.Remove(vehicleType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final Assignment1/Views/Models1/Create.cshtml
@model Final_Assignment1.Models.Model

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Engine_Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engine_Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engine_Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number_of_Doors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number_of_Doors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number_of_Doors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "VehicleType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
                @Html.ActionLink("Create Vehicle Type", "Create", "VehicleTypes")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Assignment1/Views/Models1/Delete.cshtml
@model Final_Assignment1.Models.Model

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VehicleType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engine_Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engine_Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_Doors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_Doors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final Assignment1/Views/Models1/Details.cshtml
@model Final_Assignment1.Models.Model

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VehicleType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engine_Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engine_Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number_of_Doors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number_of_Doors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ModelId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Final Assignment1/Views/Models1/Edit.cshtml
@model Final_Assignment1.Models.Model

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ModelId)

        <div class="form-group">
            @Html.LabelFor(model => model.Engine_Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engine_Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engine_Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number_of_Doors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number_of_Doors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number_of_Doors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "VehicleType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
                @Html.ActionLink("Create Vehicle Type", "Create", "VehicleTypes")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Assignment1/Views/Models1/Index.cshtml
@model IEnumerable<Final_Assignment1.Models.Model>

@{
    ViewBag.Title = "Model";
}

<h2>View models</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ModelId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Engine_Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number_of_Doors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Colour)
        </th>
        <th>
            Vehicle Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ModelId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Engine_Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number_of_Doors)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Colour)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleType.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ModelId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ModelId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ModelId })
        </td>
    </tr>
}

</table>
<style type="text/css">
    table.table {
        border-width: 3px;
        border-spacing: 2px;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: rgb(255, 255, 240);
    }

        table.table th {
            border-width: 1px;
            padding: 4px;
            border-style: double;
            border-color: gray;
            background-color: white;
        }

        table.table td {
            border-width: 1px;
            padding: 4px;
            border-style: double;
            border-color: gray;
            background-color: #e0feff;
        }

    .table td:hover {
        background-color: white;
    }
</style>