Final Assignment1/Models/Vehicle.cs
namespace Final_Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Vehicle")]
    public partial class Vehicle
    {
        public int VehicleId { get; set; }

        public int MakeId { get; set; }

        public int ModelId { get; set; }

        public int Year { get; set; }

        public decimal Price { get; set; }

        [Column(TypeName = "date")]
        public DateTime? SoldDate { get; set; }

        public virtual Make Make { get; set; }

        public virtual Model Model { get; set; }
    }
}

Final Assignment1/Models/VehicleType.cs
namespace Final_Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("VehicleType")]
    public partial class VehicleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleType()
        {
            Model = new HashSet<Model>();
        }

        public int VehicleTypeId { get; set; }

        [Required]
        [StringLength(30)]
        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Model> Model { get; set; }
    }
}

Final Assignment1/Controllers/Models1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final_Assignment1.Models;

namespace Final_Assignment1.Controllers
{
    public class Models1Controller : Controller
    {
        private OurConnection db = new OurConnection();

        // GET: Models1
        public ActionResult Index()
        {
            var model = db.Model.Include(m => m.VehicleType);
            return View(model.ToList());
        }

        // GET: Models1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: Models1/Create
        public ActionResult Create()
        {
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name");
            return View();
        }

        // POST: Models1/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModelId,Engine_Size,Number_of_Doors,Colour,VehicleTypeId")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Model.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // GET: Models1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // POST: Models1/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ModelId,Engine_Size,Number_of_Doors,Colour,VehicleTypeId")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleType, "VehicleTypeId", "Name", model.VehicleTypeId);
            return View(model);
        }

        // GET: Models1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Model.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Models1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Model.Find(id);
            db.Model.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final Assignment1/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final_Assignment1.Models;

namespace Final_Assignment1.Controllers
{
    public class VehiclesController : Controller
    {
        private OurConnection db = new OurConnection();

        // GET: Vehicles
        public ActionResult Index()
        {
            var vehicle = db.Vehicle.Include(v => v.Make).Include(v => v.Model).Include(v=>v.Model.VehicleType);
            vehicle = vehicle.OrderByDescending(v => v.Price);
            return View(vehicle.ToList());
        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicle.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles/Create
        public ActionResult Create()
        {
            //"Name" is column
            ViewBag.MakeId = new SelectList(db.Make, "MakeId", "Name");
            ViewBag.ModelId = new SelectList(db.Model, "ModelId", "ModelId");
            return View();
        }

        // POST: Vehicles/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleId,MakeId,ModelId,Year,Price,SoldDate")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Vehicle.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MakeId = new SelectList(db.Make, "MakeId", "Name", vehicle.MakeId);
            ViewBag.ModelId = new SelectList(db.Model, "ModelId", "ModelId", vehicle.ModelId);
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicle.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.MakeId = new SelectList(db.Make, "MakeId", "Name", vehicle.MakeId);
            ViewBag.ModelId = new SelectList(db.Model, "ModelId", "ModelId", vehicle.ModelId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleId,MakeId,ModelId,Year,Price,SoldDate")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MakeId = new SelectList(db.Make, "MakeId", "Name", vehicle.MakeId);
            ViewBag.ModelId = new SelectList(db.Model, "ModelId", "ModelId", vehicle.ModelId);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicle.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicle.Find(id);
            db.Vehicle.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final Assignment1/Views/Vehicles/Create.cshtml
@model Final_Assignment1.Models.Vehicle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Vehicle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MakeId, "Make Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MakeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MakeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ModelId, "ModelId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
            @Html.ActionLink("Check Model ID", "Index", "Models1")
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoldDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoldDate, new { htmlAttributes = new { @class = "form-control" ,type = "date"} })
            @Html.ValidationMessageFor(model => model.SoldDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Assignment1/Views/Vehicles/Delete.cshtml
@model Final_Assignment1.Models.Vehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Make.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final Assignment1/Views/Vehicles/Details.cshtml
@model Final_Assignment1.Models.Vehicle

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Make.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make.Name)
        </dd>

        <dt>
            Engine Size
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Engine_Size)
        </dd>

        <dt>
            Number of Doors
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Number_of_Doors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model.VehicleType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.VehicleType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Final Assignment1/Views/Vehicles/Edit.cshtml
@model Final_Assignment1.Models.Vehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VehicleId)

        <div class="form-group">
            @Html.LabelFor(model => model.MakeId, "MakeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MakeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModelId, "ModelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
                @Html.ActionLink("Check Model ID", "Index", "Models1")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.SoldDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final Assignment1/Views/Vehicles/Index.cshtml
@model IEnumerable<Final_Assignment1.Models.Vehicle>

@{
    ViewBag.Title = "All vehicles";
}

<h2>View all vehicles</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Make.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model.Engine_Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model.Number_of_Doors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model.Colour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model.VehicleType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoldDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Make.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Engine_Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Number_of_Doors)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Colour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model.VehicleType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoldDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.VehicleId }) |
                @Html.ActionLink("Details", "Details", new { id = item.VehicleId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.VehicleId })
            </td>
        </tr>
    }

</table>
<style type="text/css">
    table.table {
        border-width: 3px;
        border-spacing: 2px;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: rgb(255, 255, 240);
    }

        table.table th {
            border-width: 1px;
            padding: 4px;
            border-style: double;
            border-color: gray;
            background-color: white;
        }

        table.table td {
            border-width: 1px;
            padding: 4px;
            border-style: double;
            border-color: gray;
            background-color: #e0feff;
        }

    .table td:hover {
        background-color: white;
    }
</style>